# Generated by Django 3.0.4 on 2020-07-29 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstName', models.CharField(max_length=3)),
                ('lastName', models.CharField(max_length=255)),
                ('email', models.EmailField(blank=True, max_length=255)),
                ('ico', models.CharField(max_length=3)),
            ],
        ),
    ]
