# Generated by Django 3.0.4 on 2020-07-29 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Employee',
            new_name='Enterpreneur',
        ),
    ]
