# Generated by Django 3.0.8 on 2020-09-16 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urlparser', '0004_auto_20200916_1150'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='url',
            field=models.CharField(max_length=100),
        ),
    ]
